#ifndef COMM_PROTO_H
#define COMM_PROTO_H

/*******************************/

/*
 * Message body:
 * [MESSAGE_START][MESSAGE_TYPE][DATA_COUNT][DATA0][DATA1][DATA...]
 */

#define MESSAGE_START 0x1E
#define MESSAGE_END 0x1D

#define MESSAGE_PING 0x3A
#define MESSAGE_PONG 0x3B

#define MESSAGE_GET_HEALTH_AND_STATUS 0x2A
#define MESSAGE_HEALTH_AND_STATUS 0x2C

#define MESSAGE_CURRENT_TRESHOLD 0x2D
#define MESSAGE_SET_CURRENT_TRESHOLD 0x2E
#define MESSAGE_GET_CURRENT_TRESHOLD 0x2B

#define MESSAGE_ENABLE_POWER_SUPPLY 0x31
#define MESSAGE_DISABLE_POWER_SUPPLY 0x32

#endif

